### ISSUE TITLE
Como usar a biblioteca ?

### ISSUE THREAD

**Issue by hackin88** [danielcosta/redecard-ecommerce#10]
Ola

Boa Tarde

Como usar a biblioteca ?

Se possível crie uma pasta exemplos contendo os exemplos de uso da biblioteca 

Obrigado

**Comment by danielcosta** [comment]
Olá @hackin88,

Você não obteve sucesso com os exemplos que estão na [Wiki](https://github.com/danielcosta/redecard-ecommerce/wiki)?

Caso não, em que passo está tendo problema?

Abs.

**Comment by hackin88** [comment]
Ola Boa Tarde

Eu não tinha visto essas informações

Assim que possível estarei efetuando alguns testes

Obrigado

**Comment by danielcosta** [comment]
Blz, se houver qualquer outra dúvida no uso pode me enviar!
