### ISSUE TITLE
Dados de configuração

### ISSUE THREAD

**Issue by lucascolette** [danielcosta/redecard-ecommerce#11]
Olá, além do número do estabelecimento, o que mais preciso para efetuar a autenticação com o webservice?

**Comment by danielcosta** [comment]
Olá, de acordo com a documentação do nosso [Wiki](https://github.com/redecard/redecard-ecommerce/wiki):

`$authentication = new Authentication('987654321234567890', 'mYSeCr3t');`

**Comment by lucascolette** [comment]
@danielcosta o que seria o primeiro e segundo parâmetro? Usuário e senha do lojista que a Rede fornece?

**Comment by danielcosta** [comment]
Exato! É só usar o número do estabelecimento Rede e a senha fornecida por eles/alterada pela loja.

São os dados da seção 2.1.1.1.1 [deste manual](https://www.userede.com.br/pt-BR/produtosservicos/Documents/Ecommerce/05_Manual_E-Guia_do_Desenvolvedor_eRede_140602.pdf).

**Comment by lucascolette** [comment]
Legal! @danielcosta existe alguma credencial teste?

**Comment by danielcosta** [comment]
Eles não divulgam nenhuma credencial nas documentações, é preciso obter direto com eles...

**Comment by lucascolette** [comment]
@danielcosta legal! Eu percebi que não é necessário informar a bandeira do cartão. A biblioteca identifica automaticamente pelo número?

**Comment by danielcosta** [comment]
Apesar de existirem algumas regras para sabermos a bandeira do cartão apartir do BIN ([exemplo](https://gist.github.com/erikhenrique/5931368)), não requisição não enviamos essa informação. Eles é que respondem a bandeira, dependendo da resposta.

**Comment by lucascolette** [comment]
Obrigado @danielcosta
