### ISSUE TITLE
Indisponibilidade do webservice

### ISSUE THREAD

**Issue by lucascolette** [danielcosta/redecard-ecommerce#12]
@danielcosta o webservice está indisponível? O endpoint é https://scommerce.redecard.com.br/Beta/wsTransaction, certo?

**Comment by romulets** [comment]
To com o mesmo problema :/

**Comment by lucascolette** [comment]
@romulets este é o ambiente de teste e parece que está fora mesmo. Fiz um teste e consegui simular algo no ambiente de produção. Tive que utilizar o método abaixo:

`$redecard->setEndpoint('https://ecommerce.userede.com.br/Transaction/wsTransaction');`

**Comment by romulets** [comment]
Você usou quais credencias para teste nesse webservice? Eu to estou tentando acessar a documentação mas ta dando not found pra mim :/

**Comment by lucascolette** [comment]
Creio que não há credenciais de teste. Pelo menos não achei isso na documentação.

**Comment by romulets** [comment]
Pode passar a documentação que está consultando? Obrigado!

**Comment by romulets** [comment]
Estava dando uma olhada em [outra documentação](https://www.userede.com.br/Desenvolvedores/Paginas/manual.html#configuracoes) que achei (inclusive com outra biblioteca PHP :/) , e o padrão para o ambiente de desenvolvimento é o domínio ser scommerce e não ecommerce (ficaria https://scommerce.userede.com.br/Transaction/wsTransaction) . Não sei se esse realmente é o ambiente de desenvolvimento correto, mas ta ai a dica kkk

**Comment by danielcosta** [comment]
Pessoal, o endpoint padrão no código-fonte ainda aponta para o antigo domínio redecard.com.br, é preciso usar os novos (desde 2014) endpoints ao instanciar o Client, que são:

Teste - https://scommerce.userede.com.br/Transaction/wsTransaction
Produção - https://ecommerce.userede.com.br/Transaction/wsTransaction

Podem testar?

**Comment by romulets** [comment]
A transação ta dando certinho agora! Porém, estou tendo problemas com as credenciais. Existe alguma para teste?

**Comment by danielcosta** [comment]
As credenciais são fornecidas exclusivamente pela Rede.
