### ISSUE TITLE
Sobre o tipo da integração

### ISSUE THREAD

**Issue by mozgbrasil** [danielcosta/redecard-ecommerce#13]
Ola

Bom dia

Em

https://www.userede.com.br/

Vemos que é oferecido os serviços

Soluções para lojas online
- Rede Pay
- e.Rede

Essa biblioteca é relativo ao e-Rede ?

Como esse repositório é oficial da Redecard vocês pretendem desenvolver o SDK para as demais soluções ?

E quanto ao Komerci, sabe me informar porque o mesmo não se encontra na lista oferecida pela Redecard ?

**Comment by danielcosta** [comment]
Olá @mozgbrasil, tudo bem? Esse repositório é referente ao e-Rede sim (antigo Redecard Ecommerce), e você consegue achar no github outras libs que atendem tanto o Komerci quanto o Rede Pay. Por enquanto ainda não vamos trazer essas libs pra cá por terem sido feitas por outros desenvolvedores.
